package passroutebackend.user.entity;

public enum JobType {
    BACKEND_DEVELOPER,
    FRONTEND_DEVELOPER,
    FULLSTACK_DEVELOPER,
    MOBILE_DEVELOPER,
    DATA_ENGINEER,
    DATA_SCIENTIST,
    AI_ML_ENGINEER,
    DEVOPS_ENGINEER,
    SECURITY_ENGINEER,
    QA_ENGINEER,
    PRODUCT_MANAGER,
    UI_UX_DESIGNER,
    GAME_DEVELOPER,
    EMBEDDED_DEVELOPER,
    BLOCKCHAIN_DEVELOPER,
    SYSTEM_ENGINEER,
    DBA
}
