package passroutebackend.user.entity;

public enum JobType {
    BACKEND_DEVELOPER,
    FRONTEND_DEVELOPER,
    WEB_DEVELOPER,
    APP_DEVELOPER,
    SYSTEM_ENGINEER,
    NETWORK_ENGINEER,
    DBA,
    DATA_ENGINEER,
    DATA_SCIENTIST,
    SECURITY_ENGINEER,
    SOFTWARE_DEVELOPER,
    GAME_DEVELOPER,
    HARDWARE_DEVELOPER,
    AI_ML_ENGINEER,
    BLOCKCHAIN_DEVELOPER,
    CLOUD_ENGINEER,
    PROMPT_ENGINEER,
    AI_SECURITY_SPECIALIST,
    MLOPS_ENGINEER,
    AI_SERVICE_DEVELOPER
}
